config/routes.rb
Rails.application.routes.draw do
  root to: "employees#index"
  resources :bills, except: %i[show]
  resources :employees, except: %i[show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :employee
  enum bill_type: { food: 0, travel: 1, others: 2 }

  validates :amount, :bill_type, presence: true

  delegate :full_name, to: :employee, prefix: true
  delegate :department_name, to: :employee, prefix: true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  has_many :bills, dependent: :destroy

  validates :first_name, :last_name, :email, presence: true
  delegate :name, to: :department, prefix: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[edit update destroy ]

  # GET /bills or /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1 or /bills/1.json
  # def show
  # end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bills_url, notice: 'Bill was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bills_url, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy!

    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:amount, :bill_type, :employee_id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  # def show
  # end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, notice: 'Employee was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :designation, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/bills/_form.html.erb
<%= form_with(model: bill) do |form| %>
  <% if bill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row my-3">
    <div  class="col-3">
      <%= form.label :bill_type, "Type", class: 'mb-2' %>
      <%= form.collection_select(:bill_type, Bill.bill_types.map{ |dp| [dp.first, dp.first.humanize] }, :first, :second, {:prompt => 'Type'},{:class=>'form-control custom-select'}) %>
    </div>
    <div  class="col-3">
      <%= form.label :amount, class: 'mb-2' %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1" style="border-radius: 4px 0px 0px 4px">INR</span>
        </div>
        <%= form.number_field :amount, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row my-3">
    <div class='col-6'>
      <%= form.label :employee_id, class: 'mb-2'%>
      <%= form.collection_select(:employee_id,  Employee.all, :id, :full_name, {:prompt => 'Select Employee'},{:class=>'form-control custom-select'}) %>
    </div>
  </div>


  <div class="d-flex my-4">
    <%= form.submit class: 'btn btn-primary'%>
    <%= link_to 'Back', bills_path, class: 'btn btn-secondary mx-3' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render "form", bill: @bill %>

app/views/bills/index.html.erb
<%if notice.present? %>
  <p style="color: green"><%= notice %></p>
<%end%>
<div class="d-flex justify-content-between align-items-center mb-4">

  <h1>Bills</h1>

  <div>
    <%= link_to "New", new_bill_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="table-responsive">


  <table class="table table-striped table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col">Type</th>
        <th scope="col">Amount</th>
        <th scope="col">Date of Submission</th>
        <th scope="col">Submitter</th>
        <th scope="col">Department</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @bills.each do |bill| %>
        <tr style="vertical-align: middle">
          <td><%= bill.bill_type.humanize %></td>
          <td><%= bill.amount %></td>
          <td><%= bill.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= bill.employee_full_name %></td>
          <td><%= bill.employee_department_name %></td>
          <td>
            <div class="d-flex">

              <%= link_to 'Edit', edit_bill_path(bill), class: 'btn btn-outline-primary' %>
              <%= button_to "Delete", bill, method: :delete, class: 'btn btn-outline-danger mx-2' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render "form", bill: @bill %>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row my-3">
    <div class="col-3">
      <%= form.label :first_name, class: 'mb-2'%>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="col-3">
      <%= form.label :last_name, class: 'mb-2' %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="col-6">
      <%= form.label :email, class: 'mb-2' %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1" style="border-radius: 4px 0px 0px 4px">@</span>
        </div>
        <%= form.email_field :email, class: 'form-control' %>
      </div>

    </div>
  </div>


  <div class="row my-3">
    <div  class="col-3">
      <%= form.label :designation, class: 'mb-2' %>
      <%= form.text_field :designation, class: 'form-control' %>
    </div>

    <div  class="col-4">
      <%= form.label :department_id, "Department", class: 'mb-2' %>
      <%= form.collection_select(:department_id,  Department.all, :id, :name, {:prompt => 'Select Department'},{:class=>'form-control custom-select'}) %>
    </div>
  </div>

  <div class="d-flex">
    <%= form.submit class: 'btn btn-primary'%>
    <%= link_to 'Back', redirect_path, class: 'btn btn-secondary mx-3' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit employee</h1>

<%= render "form", employee: @employee, redirect_path: employees_path %>

app/views/employees/index.html.erb
<%if notice.present? %>
  <p style="color: green"><%= notice %></p>
<%end%>
<div class="d-flex justify-content-between align-items-center mb-4">

  <h1>Employees</h1>

  <div>
    <%= link_to "New", new_employee_path, class: "btn btn-primary" %>
  </div>
</div>

<table class="table table-striped table-bordered">
  <thead class="thead-light">
    <tr>
      <th scope="col">Full Name</th>
      <th scope="col">Designation</th>
      <th scope="col">Department</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr style="vertical-align: middle">
        <td><%= employee.full_name %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.department_name %></td>
        <td>
          <div class="d-flex" style="width: 0">

            <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-outline-primary' %>
            <%= button_to "Delete", employee, method: :delete, class: 'btn btn-outline-danger mx-2' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee, redirect_path: employees_path %>

app/views/layouts/_navbar.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="/culture_monkey_logo.svg" class="d-inline-block align-top" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Employees', employees_path, class: "nav-link #{'active' if current_page?(employees_path) || controller_name == 'employees'}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Bills', bills_path, class: "nav-link #{'active' if current_page?(bills_path) || controller_name == 'bill'}" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeReimbursementBootstrap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container my-4">
      <%= yield %>
    </div>
  </body>
</html>